# Generated by Django 4.2.1 on 2023-05-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='porters/')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=300)),
                ('operating_system', models.CharField(max_length=200)),
                ('prosessor', models.CharField(max_length=200)),
                ('ram', models.IntegerField(default=0)),
                ('memory_size', models.IntegerField(default=0)),
                ('videocard', models.CharField(max_length=100)),
                ('screen_size', models.FloatField(default=0)),
                ('bluetooth', models.BooleanField()),
                ('wifi', models.BooleanField(default=True)),
                ('connection', models.BooleanField()),
                ('weight', models.FloatField(default=0)),
                ('warranty', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
