# Generated by Django 4.2.1 on 2023-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultracomp', '0002_alter_laptopmodel_bluetooth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
