# Generated by Django 4.2.1 on 2023-06-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultracomp', '0004_alter_laptopmodel_options_alter_laptopmodel_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopmodel',
            name='weight',
        ),
    ]
