# Generated by Django 4.2.1 on 2023-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultracomp', '0005_remove_laptopmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopmodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
