# Generated by Django 4.2.1 on 2023-06-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultracomp', '0008_commentmodel_parent_alter_commentmodel_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laptop_comments', to='ultracomp.laptopmodel'),
        ),
    ]
